config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :entries

  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  category   :string
#  content    :text
#  created_at :datetime         not null
#  id         :bigint(8)        not null, primary key
#  ig_handle  :string
#  name       :string
#  updated_at :datetime         not null
#

class Entry < ApplicationRecord
    CATEGORY = [ "MUA", "MODEL" ]
    has_one_attached :main_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry, notice: "Entry was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /entries/1
  def update
  puts Rails.application.credentials[:aws][:secret_access_key]
  puts Rails.application.credentials[:aws][:access_key_id]
    if @entry.update(entry_params)
      redirect_to @entry, notice: "Entry was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to entries_url, notice: "Entry was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entry_params
      params.require(:entry).permit(:name, :content, :category, :ig_handle, :main_image)
    end
end

app/controllers/errors_controller.rb
# Render error pages
class ErrorsController < ApplicationController
  layout false

  def route_not_found
    render file: Rails.public_path.join("404.html"), status: :not_found
  end
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/javascript_helper.rb
module JavascriptHelper
  # Adds the async attribute into javascript_include_tag, but only when the
  # asset pipeline is not in debug mode. Be careful when using this helper,
  # because async <script> tags have no load order guarantees.
  #
  # See also: http://www.html5rocks.com/en/tutorials/speed/script-loading/
  def javascript_include_async_tag(*args)
    options = args.extract_options!

    unless options["debug"] != false && request_debug_assets?
      options[:async] = true
    end

    javascript_include_tag(*args, options)
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(file: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/navbar_helper.rb
module NavbarHelper
  # Generate <li><a href=...></a></li> appropriate for the Bootstrap navbar.
  # If :active_when hash is provided in the options, a class=active will
  # automatically be added to the <li> when appropriate.
  #
  # Example:
  #
  #     <%= navbar_link_to(
  #           "Home",
  #           root_path,
  #           active_when: { controller: "home" }) %>
  #
  def navbar_link_to(label, path, options={})
    active_when = options.delete(:active_when) { {} }
    active = active_when.all? do |key, value|
      case value
      when Regexp
        params[key].to_s =~ value
      else
        params[key].to_s == value
      end
    end

    content_tag(:li, class: ("active" if active)) do
      link_to(label, path, options)
    end
  end
end

app/helpers/retina_image_helper.rb
module RetinaImageHelper
  # Like the Rails image_tag, but adds a srcset attribute with an @2x version
  # of the image, thereby ensuring the image looks great on retina devices.
  # Assumes that the retina version of the image is named the same with "@2x"
  # before the extension, like "image@2x.png". For example:
  #
  #   <%= retina_image_tag("logo.png") %>
  #
  # Produces:
  #
  #   <img src="/assets/logo.png"
  #        srcset="/assets/logo.png 1x,/assets/logo@2x.png 2x">
  #
  # The srcset attribute is supported by modern desktop browsers and iOS 8+.
  def retina_image_tag(src, options={})
    src_1x = image_path(src)
    src_2x = image_path(src.sub(/^(.*)(\.[^\.]+)$/, '\1@2x\2'))
    srcset = "#{src_1x} 1x,#{src_2x} 2x"

    image_tag(src, options.reverse_merge(srcset: srcset, alt: ""))
  end
end

app/views/entries/_form.html.erb
<%= bootstrap_form_for(@entry, multipart: true) do |f| %>

  <%= f.alert_message "Please review the problems below:" %>

  <%= f.text_field :name %>
  <%= f.text_area :content, rows: 5 %>
  <%= f.select :category, Entry::CATEGORY, include_blank: false %>
  <%= f.text_field :ig_handle %>
  <div class="field">
    add an image....
    <%= f.file_field :main_image %>
  </div>

  <%= f.primary %>
  <%= link_to "Back", entries_path, class: "btn btn-link" %>

<% end %>

app/views/entries/edit.html.erb
<% provide(:title, "Editing entry") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/entries/index.html.erb
<!-- <% provide(:title, "Listing entries") %> -->

<!-- Portfolio Grid -->
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Portfolio</h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row">
        <% @entries.each do |entry| %>
      <div class="col-md-4 col-sm-6 portfolio-item" style="    background: white;
      text-align: center;">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal<%= entry.id %>">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fas fa-plus fa-3x"></i>
            </div>
          </div>
          <%= image_tag entry.main_image.attached? ? url_for(entry.main_image) : '', class: "img-fluid" %>
          <!-- <img class="img-fluid" src="/img/portfolio/01-thumbnail.jpg" alt=""> -->
        </a>
        <div class="portfolio-caption">
          <h4><%= entry.name %></h4>
          <p class="text-muted"><%= entry.category %></p>
        </div>
      </div>
      <% end %>
    
    </div>
    
 
</section>

<% if false %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Image</th>
      <th>Category</th>
      <th>Ig handle</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.content %></td>
        <td><%#= image_tag(entry.image_url(:thumb).to_s) %></td>
        
        <td><%= entry.category %></td>
        <td><%= entry.ig_handle %></td>
        <td>
          <div class="btn-group">
            <%= link_to entry, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_entry_path(entry), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to entry, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this entry?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_entry_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Entry") %>
<% end %>


<% end  %>







<% @entries.each do |entry| %>
  <div class="portfolio-modal modal fade" id="portfolioModal<%= entry.id %>" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="close-modal" data-dismiss="modal">
            <div class="lr">
              <div class="rl"></div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto">
                <div class="modal-body">
                  <!-- Project Details Go Here -->
                  <h2 class="text-uppercase"><%= entry.name %></h2>
                  <p class="item-intro text-muted"> <%= entry.category %></p>
                  <%= image_tag entry.main_image.attached? ? url_for(entry.main_image) : '', class: "img-fluid d-block mx-auto" %>
                  <p><%= entry.ig_handle %></p>
                  <!-- <ul class="list-inline">
                    <li>Date: January 2017</li>
                    <li>Client: Threads</li>
                    <li>Category: Illustration</li>
                  </ul> -->
                  <button class="btn btn-primary" data-dismiss="modal" type="button">
                    <i class="fas fa-times"></i>
                    Close Project</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
     
</div>
<% end %>

app/views/entries/new.html.erb
<% provide(:title, "New entry") %>



<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/entries/show.html.erb
<% provide(:title) do %>
  Entry #<%= @entry.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Name</th>
      <td><%= @entry.name %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Content</th>
      <td><%= @entry.content %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Category</th>
      <td><%= @entry.category %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Ig handle</th>
      <td><%= @entry.ig_handle %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Image</th>
      <td>
                                  
            <%= image_tag @entry.main_image.attached? ? url_for(@entry.main_image) : '' %>

    </tr>
    
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_entry_path(@entry), class: "btn btn-primary" %>
  <%= link_to "Back", entries_path, class: "btn btn-link" %>
</p>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<p>  <%= link_to "See all entries", entries_url %> </p>
<p>  <%= link_to "Create a new entry", new_entry_url %> </p>

app/views/layouts/application.html.erb
<%# The "application" layout is the default layout. It extends "base"  %>
<%# to include things like header, footer, and alerts that are common  %>
<%# to most (but not all) views.                                       %>



  <%= render("shared/flash") %>
  <%#= render("shared/page_header") %>

  <%= yield %>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mua <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->

  <%# CSS should go closest to the top of the document as possible. %>
  <%= stylesheet_link_tag("application",
                            media: "all",
                            "data-turbolinks-track" => "reload") %>

  <%# JavaScript must be in head for Turbolinks to work. %>
  <%= javascript_include_async_tag("application",
                                    "data-turbolinks-track" => "reload") %>

  <%= yield(:head) %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%# Specifies the default name of home screen bookmark in iOS 6+ %>
  <meta name="apple-mobile-web-app-title" content="Mua">

  <%= csrf_meta_tags %>

  <title>
    <%= strip_tags(yield(:title)) + " ÔøΩ " if content_for?(:title) %>
    Mua
  </title>

  <!-- Bootstrap core CSS -->
  <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="/css/agency.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">InstantBooth</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Services</a>
          </li>
          <%# <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#team">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a> %>
          <%# </li> %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <%# <header class="masthead">
      <div class="container">
        <div class="intro-text">
          <div class="intro-lead-in">Welcome To Our Studio!</div>
          <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
          <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a>
        </div>
      </div>
    </header> %>

  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <%= yield %>
        </div>
      </div>
    </div>
  </section>




  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy; Your Website 2018</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- Portfolio Modals -->

  <!-- Modal 1 -->


  <!-- Bootstrap core JavaScript -->
  <script src="/vendor/jquery/jquery.min.js"></script>
  <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Contact form JavaScript -->
  <script src="/js/jqBootstrapValidation.js"></script>
  <script src="/js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="/js/agency.min.js"></script>

</body>

</html>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© Mua <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Mua", root_path, class: "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= navbar_link_to("Home",
                           root_path,
                           active_when: { controller: "home" }) %>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Log in</a></li>
        <li><a href="#">Register</a></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% else %>
    <h1>Untitled</h1>
    <p>Don’t forget to set <code>provide(:title)</code> for this view!</p>
  <% end %>
</div>